/**
 * topicsDB.ts
 * Central data service for the Discovery Hub.
 * All 18 financial topics with learner counts, growth %, discussion counts,
 * trending flags, and mappings to related simulations and community tags.
 */

export interface FinancialTopic {
  id: string;
  label: string;
  emoji: string;
  color: string; // Tailwind bg color class
  glowColor: string; // Tailwind shadow/ring color class
  textColor: string;
  learnerCount: number;
  discussionCount: number;
  growthPercent: number; // week-over-week growth
  trending: boolean;
  relatedSlugs: string[]; // simulation slugs from learn/[slug]
  communityTags: string[]; // tags to match against community posts
  description: string;
}

export const FINANCIAL_TOPICS: FinancialTopic[] = [
  {
    id: 'index-investing',
    label: 'Index Investing',
    emoji: '📊',
    color: 'bg-blue-50',
    glowColor: 'hover:shadow-blue-200 hover:ring-blue-300',
    textColor: 'text-blue-700',
    learnerCount: 3241,
    discussionCount: 187,
    growthPercent: 28,
    trending: true,
    relatedSlugs: ['index-fund-simulator', 'sip-growth', 'compound-interest'],
    communityTags: ['indexfunds', 'investing', 'nifty50'],
    description: 'Learn to invest passively with diversified index funds',
  },
  {
    id: 'mutual-funds',
    label: 'Mutual Funds',
    emoji: '🏦',
    color: 'bg-indigo-50',
    glowColor: 'hover:shadow-indigo-200 hover:ring-indigo-300',
    textColor: 'text-indigo-700',
    learnerCount: 1980,
    discussionCount: 143,
    growthPercent: 14,
    trending: false,
    relatedSlugs: ['mutual-fund-builder', 'sip-growth'],
    communityTags: ['mutualfunds', 'sipinvesting', 'debtfunds'],
    description: 'Navigate the universe of mutual fund schemes',
  },
  {
    id: 'sips',
    label: 'SIPs',
    emoji: '🔄',
    color: 'bg-cyan-50',
    glowColor: 'hover:shadow-cyan-200 hover:ring-cyan-300',
    textColor: 'text-cyan-700',
    learnerCount: 2740,
    discussionCount: 210,
    growthPercent: 22,
    trending: true,
    relatedSlugs: ['sip-growth', 'compound-interest'],
    communityTags: ['sip', 'sipinvesting', 'FirstSIP'],
    description: 'Build wealth steadily through Systematic Investment Plans',
  },
  {
    id: 'emergency-funds',
    label: 'Emergency Funds',
    emoji: '🛡️',
    color: 'bg-teal-50',
    glowColor: 'hover:shadow-teal-200 hover:ring-teal-300',
    textColor: 'text-teal-700',
    learnerCount: 1825,
    discussionCount: 98,
    growthPercent: 31,
    trending: true,
    relatedSlugs: ['emergency-fund', 'budget-crisis'],
    communityTags: ['EmergencyFund', 'savings', 'financialsafety'],
    description: 'Build a financial safety net for life\'s surprises',
  },
  {
    id: 'budgeting',
    label: 'Budgeting',
    emoji: '📋',
    color: 'bg-green-50',
    glowColor: 'hover:shadow-green-200 hover:ring-green-300',
    textColor: 'text-green-700',
    learnerCount: 2150,
    discussionCount: 162,
    growthPercent: 9,
    trending: false,
    relatedSlugs: ['budget-crisis', 'emergency-fund'],
    communityTags: ['budgeting', 'savings', '50-30-20'],
    description: 'Master the 50-30-20 rule and zero-based budgeting',
  },
  {
    id: 'retirement-planning',
    label: 'Retirement Planning',
    emoji: '🌴',
    color: 'bg-amber-50',
    glowColor: 'hover:shadow-amber-200 hover:ring-amber-300',
    textColor: 'text-amber-700',
    learnerCount: 1640,
    discussionCount: 122,
    growthPercent: 19,
    trending: true,
    relatedSlugs: ['retirement-planner', 'sip-growth', 'compound-interest'],
    communityTags: ['retirement', 'FIRE', 'NPS'],
    description: 'Plan your path to a financially secure retirement',
  },
  {
    id: 'insurance',
    label: 'Insurance',
    emoji: '☂️',
    color: 'bg-sky-50',
    glowColor: 'hover:shadow-sky-200 hover:ring-sky-300',
    textColor: 'text-sky-700',
    learnerCount: 987,
    discussionCount: 74,
    growthPercent: 6,
    trending: false,
    relatedSlugs: ['insurance-decision'],
    communityTags: ['insurance', 'termplan', 'health'],
    description: 'Protect what you\'ve built with the right coverage',
  },
  {
    id: 'tax-planning',
    label: 'Tax Planning',
    emoji: '🧾',
    color: 'bg-slate-50',
    glowColor: 'hover:shadow-slate-200 hover:ring-slate-300',
    textColor: 'text-slate-700',
    learnerCount: 1320,
    discussionCount: 89,
    growthPercent: 12,
    trending: false,
    relatedSlugs: ['tax-planning'],
    communityTags: ['taxsaving', '80c', 'ELSS'],
    description: 'Legally minimize your tax burden and maximize savings',
  },
  {
    id: 'wealth-building',
    label: 'Wealth Building',
    emoji: '💎',
    color: 'bg-purple-50',
    glowColor: 'hover:shadow-purple-200 hover:ring-purple-300',
    textColor: 'text-purple-700',
    learnerCount: 2890,
    discussionCount: 201,
    growthPercent: 17,
    trending: false,
    relatedSlugs: ['compound-interest', 'mutual-fund-builder', 'future-you'],
    communityTags: ['wealthbuilding', 'investing', 'compounding'],
    description: 'Compound your way to long-term financial freedom',
  },
  {
    id: 'fire',
    label: 'FIRE',
    emoji: '🔥',
    color: 'bg-orange-50',
    glowColor: 'hover:shadow-orange-200 hover:ring-orange-300',
    textColor: 'text-orange-700',
    learnerCount: 1455,
    discussionCount: 176,
    growthPercent: 35,
    trending: true,
    relatedSlugs: ['retirement-planner', 'future-you', 'side-hustle'],
    communityTags: ['FIRE', 'financialindependence', 'earlyretirement'],
    description: 'Financial Independence, Retire Early — the movement explained',
  },
  {
    id: 'behavioral-finance',
    label: 'Behavioral Finance',
    emoji: '🧠',
    color: 'bg-fuchsia-50',
    glowColor: 'hover:shadow-fuchsia-200 hover:ring-fuchsia-300',
    textColor: 'text-fuchsia-700',
    learnerCount: 870,
    discussionCount: 63,
    growthPercent: 8,
    trending: false,
    relatedSlugs: ['market-crash', 'lifestyle-inflation'],
    communityTags: ['psychology', 'biases', 'decisions'],
    description: 'Understand why we make irrational financial decisions',
  },
  {
    id: 'asset-allocation',
    label: 'Asset Allocation',
    emoji: '⚖️',
    color: 'bg-violet-50',
    glowColor: 'hover:shadow-violet-200 hover:ring-violet-300',
    textColor: 'text-violet-700',
    learnerCount: 1240,
    discussionCount: 87,
    growthPercent: 11,
    trending: false,
    relatedSlugs: ['mutual-fund-builder', 'market-crash'],
    communityTags: ['assetallocation', 'rebalancing', 'portfolio'],
    description: 'Balance risk and reward across asset classes',
  },
  {
    id: 'personal-finance',
    label: 'Personal Finance',
    emoji: '💰',
    color: 'bg-emerald-50',
    glowColor: 'hover:shadow-emerald-200 hover:ring-emerald-300',
    textColor: 'text-emerald-700',
    learnerCount: 4120,
    discussionCount: 312,
    growthPercent: 5,
    trending: false,
    relatedSlugs: ['emergency-fund', 'budget-crisis', 'lifestyle-inflation'],
    communityTags: ['personalfinance', 'money', 'savings'],
    description: 'Master your relationship with money from the ground up',
  },
  {
    id: 'debt-management',
    label: 'Debt Management',
    emoji: '🏋️',
    color: 'bg-red-50',
    glowColor: 'hover:shadow-red-200 hover:ring-red-300',
    textColor: 'text-red-700',
    learnerCount: 1060,
    discussionCount: 91,
    growthPercent: 7,
    trending: false,
    relatedSlugs: ['loan-repayment', 'credit-score-builder'],
    communityTags: ['debt', 'loanrepayment', 'creditcard'],
    description: 'Pay off debt faster with avalanche and snowball strategies',
  },
  {
    id: 'stock-market',
    label: 'Stock Market Basics',
    emoji: '📈',
    color: 'bg-lime-50',
    glowColor: 'hover:shadow-lime-200 hover:ring-lime-300',
    textColor: 'text-lime-700',
    learnerCount: 3650,
    discussionCount: 265,
    growthPercent: 20,
    trending: false,
    relatedSlugs: ['market-crash', 'index-fund-simulator'],
    communityTags: ['stocks', 'equities', 'NSE'],
    description: 'Understand how the stock market works and how to invest',
  },
  {
    id: 'etfs',
    label: 'ETFs',
    emoji: '🗂️',
    color: 'bg-blue-50',
    glowColor: 'hover:shadow-blue-200 hover:ring-blue-300',
    textColor: 'text-blue-600',
    learnerCount: 1120,
    discussionCount: 78,
    growthPercent: 15,
    trending: false,
    relatedSlugs: ['index-fund-simulator', 'mutual-fund-builder'],
    communityTags: ['ETF', 'goldetf', 'lowcost'],
    description: 'Trade index funds on the stock exchange with low costs',
  },
  {
    id: 'goal-setting',
    label: 'Goal Setting',
    emoji: '🎯',
    color: 'bg-pink-50',
    glowColor: 'hover:shadow-pink-200 hover:ring-pink-300',
    textColor: 'text-pink-700',
    learnerCount: 2210,
    discussionCount: 134,
    growthPercent: 10,
    trending: false,
    relatedSlugs: ['future-you', 'sip-growth'],
    communityTags: ['goals', 'financialgoals', 'planning'],
    description: 'Set SMART financial goals and build a roadmap to reach them',
  },
  {
    id: 'financial-psychology',
    label: 'Financial Psychology',
    emoji: '💡',
    color: 'bg-yellow-50',
    glowColor: 'hover:shadow-yellow-200 hover:ring-yellow-300',
    textColor: 'text-yellow-700',
    learnerCount: 760,
    discussionCount: 55,
    growthPercent: 13,
    trending: false,
    relatedSlugs: ['salary-negotiation', 'lifestyle-inflation'],
    communityTags: ['psychology', 'mindset', 'habits'],
    description: 'The mental side of money — habits, biases, and mindset shifts',
  },
];

/** Top 5 trending topics by growthPercent */
export const TRENDING_TOPICS = [...FINANCIAL_TOPICS]
  .sort((a, b) => b.growthPercent - a.growthPercent)
  .slice(0, 5);

/** Top 5 by learner count — what the community is learning */
export const COMMUNITY_POPULAR = [...FINANCIAL_TOPICS]
  .sort((a, b) => b.learnerCount - a.learnerCount)
  .slice(0, 5);

/** Quick lookup by id */
export const getTopicById = (id: string) =>
  FINANCIAL_TOPICS.find((t) => t.id === id) ?? null;

/** Filter simulations by topic (returns matching slugs) */
export const getRelatedSlugs = (topicId: string): string[] =>
  getTopicById(topicId)?.relatedSlugs ?? [];
